### ISSUE TITLE
Mapview connecting lines

### ISSUE THREAD

**Issue by alazarovski** [r-spatial/mapview#131]
I have this problem when I try to plot flights with lines with mapview, but a line going from Australia towards South America across the Pacific Ocean is connected in the wrong way, also line going from Russia towards Canada across the North pole is connected in the wrong way.

Can this be fixed somehow? Removing the straight lines artificially introduced would solve my problem, but other ideas and suggestions are welcomed.

![mapview](https://user-images.githubusercontent.com/31340634/36857013-b7e28f02-1d77-11e8-8641-c2b946f4230f.PNG)

**Comment by edzer** [comment]
Never cross the dateline when flying!

**Comment by alazarovski** [comment]
Any suggestions on how to fix the plot maybe ? Much appreciated

**Comment by tim-salabim** [comment]
It is possible, however, in your example shown above would likely mean manual modification of selected lines (unless you can find a threshold that works for all lines). Consider the following example where line node coordinates are > 180. 
```r
library(sf)
library(mapview)

y = seq(-37, 37, 5)
x = seq(175, 245, 5)

pts = matrix(0, 15, 2)
pts[, 1] = x
pts[, 2] = y

ls1 = st_sfc(st_linestring(pts), crs = 4326)

mapview(ls1)
```
![screenshot at 2018-03-02 11 56 03](https://user-images.githubusercontent.com/2826432/36895858-bf2c31d4-1e10-11e8-891b-1a2e754e522b.png)

Simply setting all `y < 0` to `y + 360` wouldn't work in our case I think because then other lines that pass the prime meridian become broken. Hence, you need to carefully select the lines you want to add 360°.

**Comment by tim-salabim** [comment]
@alazarovski does this answer your question? Can we close this?

**Comment by alazarovski** [comment]
Yes. I apologize for the late reply. Thank you for your answer it was very helpful
