### ISSUE TITLE
mapview::mapview() map is grey

### ISSUE THREAD

**Issue by data-al** [r-spatial/mapview#153]
I updated my mapview package today and from this point on every object I plot has a grey background instead of a map. 

``` {r}
library(mapview)
mapview(breweries)
```
![image](https://user-images.githubusercontent.com/31340634/39534263-818508d2-4e31-11e8-8dd0-68be4aa11f95.png)

Is this a common problem ? I tried reinstalling the version from here as well:
```{r}
devtools::install_github("r-spatial/mapview@develop")
```

but still getting the same result

**Comment by tim-salabim** [comment]
yes, this is a known issue of the RStudio viewer (especially on windows). If you open the map in the browser you should see all maps. In the viewer, depending on your RStudio version, you should at least see the OpenStreetMap and ESRI imagery. You can try one of the RStudio [daily builds](https://dailies.rstudio.com/) - version 1.2. and higher - where the default CartoDB.Positron map should appear as expected.
I'm closing this here, as this cannot be fixed in mapview.
