### ISSUE TITLE
Graph popups in example doc seem to be broken

### ISSUE THREAD

**Issue by DataStrategist** [r-spatial/mapview#156]
If you click on any of the pointers on https://r-spatial.github.io/mapview/articles/articles/mapview_04-popups.html#graph-popups , you'll see the broken picture link. Thanks for an interesting package!

**Comment by DataStrategist** [comment]
A silly trick can be to save the pictures to the repo and then make
reference to the url in github.com. I've used that trick before...
unelegant as it might be.

**Comment by tim-salabim** [comment]
Yeah, that's what I've done too in the past. I could do again, but I'd rather fix this for good... Hence, I'm leaving this open as a steady reminder

**Comment by dmessmer** [comment]
I'm encountering a problem where the pop-up graphs work on your web page and in my r-studio viewer, but not when I 'knit to html' using RMarkdown.  Using the [example code](https://r-spatial.github.io/mapview/articles/articles/mapview_04-popups.html#graph-popups), I've pasted a screenshot of what I encounter below.  Any suggestions as to what the problem is?  Thanks for your work on this incredible package!

![image](https://user-images.githubusercontent.com/13224241/44925652-35e1bf80-ad0c-11e8-9ffb-914c0d469108.png)

**Comment by tim-salabim** [comment]
Will address this when I get build to pass

**Comment by DataStrategist** [comment]
need any help?
