### ISSUE TITLE
zoom-to-layer button function [Tutorial]

### ISSUE THREAD

**Issue by andzandz11** [r-spatial/mapview#213]
I sorry but it is unclear to me what this does.
It does zoom geographically to the centroid/weighted middle/zoom to include everything ...(?) of the layer, but it does not exclude other layers from view?
If layers all have the same dimension then zoom to the center does nothing if the map hasn't been moved, right?
Same as here:
https://r-spatial.github.io/mapview/articles/articles/mapview_01-basics.html#controlling-attribute-columns

**Comment by tim-salabim** [comment]
> It does zoom geographically to the centroid/weighted middle/zoom to include everything ...(?) of the layer, but it does not exclude other layers from view?
If layers all have the same dimension then zoom to the center does nothing if the map hasn't been moved, right?

That's right. The idea here is to provide quick zoom-to functionality in case there are several layers on the map with different extents, so that instead of panning manually the user can simply click on the button(s) to re-center the map on the respective layers.
If all layers have the same extent, then it is unfortunate that several buttons are placed on the map that essentially zoom to the same location. If you know this beforehand, you can for example set `homebutton = FALSE` for all but one of the layers

```r
library(mapview)

mapview(franconia, zcol = "district", homebutton = FALSE) +
  mapview(franconia, homebutton = FALSE) +
  breweries
```
To control layer visibility, you need to use the layer control at the top left of the map.
