### ISSUE TITLE
Disable resampling when plotting raster

### ISSUE THREAD

**Issue by fabeit** [r-spatial/mapview#273]
Thank you for the very nice package!
I have seen a similar question/issue https://github.com/r-spatial/mapview/issues/123 in which it is explained that any raster object is resampled to be reprojected.

I am wondering if there is anyway to turn the resampling off because it really reduced the usefulness of such great package. My rasters are usually in latlong and world coverage WGS84. Is there any way to plot the raster with mapview() without resampling? I guess I could convert the raster in a polygon but it is very useful to plot the raster along with other simple_features.

Many thanks

**Comment by tim-salabim** [comment]
You can use `native.crs = TRUE` but then you will not get backgraound maps. In order to put rasters on the background maps, we need to transform the data to webmercator, there is no way aound this (unless you find a tile provider that provides background maps in wgs84). Not sure if you are aware, but you can set `method = 'ngb'` to use neaighrest neighbor interpolation when transforming.

**Comment by fabeit** [comment]
@tim-salabim thank you for the suggestion, I didn't know about the native.crs option, unfortunately it does not provide the cell on mouse hover, and the ngb method to doesn't provide the actual values. What I end up doing is a rasterToPolygon and then use mapview that way. I might just use a wrap around function. Is there a reason why it is difficult to find background maps in WGS 84?

**Comment by tim-salabim** [comment]
> Is there a reason why it is difficult to find background maps in WGS 84?

Because pretty much all tile providers provide tiles in webmercator as it is the de-facto default for webmapping.

I still don't quite get the issue you have... If you plot polygons with mapview, they are also transformed to web mercator... Do you maybe have a reprex that shows what the issue is and why it doesn't work as you'd expect?

**Comment by fabeit** [comment]
The issue is that the raster values displayed by mapview(raster) are not the actual values in the raster, since they are interpolated. You can try this with any raster in lat/long, I can provide one if you'd like. The usefulness of mapview is also to explore data interactively, but if the displayed data is not the actual data it becomes less useful. When I convert a raster to polygon, when displayed the polygons contain the actual values.

**Comment by tim-salabim** [comment]
Ok, so there's likely no quick fix here. Unfortunately leaflet does not support raster plotting on `L.CRS.Simple`. The only fix I could think of is to try and support `addimageQuery` for `plainview` (which is used when `native.crs = TRUE`). 
This wouldn't change the fact that we won't have background maps, though. If you want background maps in any crs other than webmercator, you're pretty much on your own...

**Comment by fabeit** [comment]
this confirms my initial thought that there is no easy solution, for me the conversion to polygons seems a reasonable compromise. Thank you for this discussion.

**Comment by tim-salabim** [comment]
If you are fine your current workaround I guess we can close here. I've opened an issue [here](https://github.com/r-spatial/leafem/issues/18) to keep the imageQuery for plainview objects open as I'd like to implement that at some stage.

Thanks
