### ISSUE TITLE
consider warning when return NULL in leafgl platform

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/mapview#283]
Here is a silent NULL return when using a raster: 

https://github.com/r-spatial/mapview/blob/0902f700a772fe237abb106dc6dabc3d2737deca/R/mapView.R#L385

Same for stars, perhaps warn that there's no raster-capability in leafgl mode?

**Comment by tim-salabim** [comment]
Good point! I plan to clean all this up (on the weekend), as it also concerns `platform = "mapdeck"`. Instead of returning `NULL` I plan to emit a message/warning and automatically fall back to `platform = "leaflet"` (currently the only one that is feature complete). Though, for mapdeck, I think there is a method for raster imagery, I just haven't explored that yet.

**Comment by mdsumner** [comment]
Cool, I knew it was probably early ... but also don't have capacity for a PR rn

**Comment by tim-salabim** [comment]
No worries, there are so many little thing to iron out rn that it is best I do this in one-fell-swoop

**Comment by tim-salabim** [comment]
Done for all raster based methods, e.g.

https://github.com/r-spatial/mapview/blob/develop/R/mapView.R#L274-L284
