### ISSUE TITLE
Error in CPL_transform: crs not found: is it missing?

### ISSUE THREAD

**Issue by elgabbas** [r-spatial/mapview#300]
Hello,
I receive this error message when deploying a shiny application to `shinyapps.io`. The application contains `mapview` interactive maps. The app works fine on my local computer but failed on `shinyapps.io` server.
```
Error in CPL_transform: crs not found: is it missing?
sf layer has inconsistent datum ().
```
I can not be sure of the source of this error. Is it something related to `mapview` or `sf` or an issue with the `shinyapps.io` server?
My code does not use `st_transform` function, but probably it has to be used internally in some other functions.

I thought this because of the use of `native.crs = T`, but when I use `native.crs = F` I receive this error:
```
Warning in CPL_transform(x, crs, aoi, pipeline, reverse) :
GDAL Error 1: No PROJ.4 translation for source SRS, coordinate transformation initialization has failed.
Warning: Error in CPL_transform: OGRCreateCoordinateTransformation() returned NULL: PROJ available?
```

Cheers,
Ahmed

**Comment by edzer** [comment]
It looks like the shinyapp.io machine runs an old PROJ.4 version, and you're feeding it with an object created with sf using a newer GDAL/PROJ combo. Is that possible?

**Comment by elgabbas** [comment]
Thanks @edzer for your response,

It uses `GEOS 3.5.1`, `GDAL 2.2.2`, `PROJ 4.9.2`.Do you think this is the reason for this error?

**Comment by edzer** [comment]
It is not a problem in itself, but may be part of the problem. If you create an `sf` object in R/sf which uses PROJ 6 or 7, and then feed that object to an R instance running PROJ 4, that will not work.

**Comment by elgabbas** [comment]
I reported this to rshinyapps and I am waiting for a response. Thanks Edzer.

**Comment by edzer** [comment]
It is not their problem, it is yours.

**Comment by elgabbas** [comment]
How can I know which version of `sf` is compatible with `PROJ 4.9.2`?
Downgrading to an older version of `sf` can cause other dependency issues, isn't it?

**Comment by edzer** [comment]
See https://github.com/r-spatial/mapview/issues/300#issuecomment-644633070

**Comment by CR-Mercado** [comment]
I was able to force shinyapps.io to spit out a more detailed message. Originally I had only 1 leaflet object broken, but I started manually transforming the crs of several items with st_transform on app load and got it to break much better (previously error was a useless and incorrect st_crs(x) == st_crs(y) is FALSE -  this of course isn't true, everything is crs 4326, the problem was actually intersecting). 

Still identifying the latest version of sf that works with shinyapps.io I will post it as soon as I find out. 

Linking to GEOS 3.5.1, GDAL 2.2.2, PROJ 4.9.2
Warning in CPL_transform(x, crs, aoi, pipeline, reverse) :
  GDAL Error 1: No PROJ.4 translation for source SRS, coordinate transformation initialization has failed.
Error in value[[3L]](cond) : 
  OGRCreateCoordinateTransformation() returned NULL: PROJ available?
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

**Comment by Z3tt** [comment]
I run into the same problem today. After hours I found [this simple solution](https://stackoverflow.com/questions/61286108/error-in-cpl-transformx-crs-aoi-pipeline-reverse-ogrcreatecoordinatetrans): In your app, update the crs of the sf objects via `sf::st_crs(dat) <- x` with `x` being the EPSG you use.
