### ISSUE TITLE
Using the "|" operator, the basemap is not rendered in knitted markdown

### ISSUE THREAD

**Issue by felixhaass** [r-spatial/mapview#349]
First off, thanks for the terrific package! It has helped me a lot. 

I've stumbled across the following minor bug. When I run `mapview(breweries) | mapview(franconia)` in an rmarkdown chunk that I subsequently knit to HTML, the basemaps are missing. 

Here's the code I've used:

~~~
---
title: "Testing Leaflet Sliders"
output: html_document
---

```{r}
library(mapview)
mapview(breweries) 
```


```{r}
library(mapview)
mapview(breweries) | mapview(franconia)
```
~~~

This gives me the following output:

![image](https://user-images.githubusercontent.com/4624173/97809878-22c23580-1c70-11eb-962f-b68053503c20.png)

When I use `mapview(breweries) | mapview(franconia)` in RStudio, the Viewer Pane shows the correct basemap. 

I'm using  `mapview` version `2.9.4`. 

I tried to narrow down from where the problem originates, but no success. Any idea?

Thanks,
Felix

**Comment by tim-salabim** [comment]
Thanks @felixhaass , this is a tough one. No idea why this doesn't work. Doesn't help that we don't see any errors in the browser console... Not sure how to fix this

**Comment by trafficonese** [comment]
It seems that markdown is having problems with leaflet panes.

The following example will show no basemap in a knitted document, but if you remove `options = pathOptions (pane = "right")` the basemap appears.
Also, if you give the pane the name `tile`, it also works, so I guess markdown only looks for basemaps in the `leaflet-pane leaflet-tile-pane` class.

So I'm not so sure that the problem comes from `mapview` or `leaflet.extras2`.

```
library(leaflet)
library(leaflet.extras2)
leaflet() %>%
  addMapPane("right", zIndex = 0) %>%
  addTiles(group = "base", layerId = "baseid", options = pathOptions(pane = "right"))
```

**Comment by tim-salabim** [comment]
@trafficonese great catch! Any ideas how to resolve this? Sounds like a job for rstudio & leaflet...

**Comment by trafficonese** [comment]
Unfortunately, I don't really have a lot of experience with markdown and the entire processing pipeline to figure out where this error actually shows up. But I'm going to dig into `rmarkdown` a bit, maybe I can find out something.

**Comment by tim-salabim** [comment]
Well, I'd say that given that you've isolated the problem to be either **leaflet** or **rmarkdown** based, we should consider opening an issue with rstudio (probably leaflet).

FWIW, this works
```r
library(leaflet)
leaflet() %>%
  addMapPane("tile", zIndex = 0) %>%
  addTiles(group = "base", layerId = "baseid", options = tileOptions(pane = "tile"))
```
whereas this doesn't
```r
library(leaflet)
leaflet() %>%
  addMapPane("right", zIndex = 0) %>%
  addTiles(group = "base", layerId = "baseid", options = tileOptions(pane = "right"))
```
I used `tileOptions` instead of `pathOptions` as I think it's better suited for `addTiles`

**Comment by cderv** [comment]
FWIW I looked a bit into that as you opened an issue in **rmarkdown**. I believe this is something missingin Leaflet JS library.
See https://github.com/rstudio/rmarkdown/issues/1949#issuecomment-1006706451

Not sure what could be done on our side, but if something, I would say it would be in **leaflet** R package by patching the CSS.

**Comment by cderv** [comment]
We've decided to add the missing CSS in **leaflet**. Hopefully this is enough to help with your issue. 

See https://github.com/rstudio/leaflet/pull/770

**Comment by tim-salabim** [comment]
Should work now with the dev version of leaflet https://github.com/rstudio/leaflet/pull/770
