### ISSUE TITLE
Issue when plotting a numeric variable

### ISSUE THREAD

**Issue by Robinlovelace** [r-spatial/mapview#350]
Not quite sure what the cause of this is, but seems like a bug so thought it worth reporting:

``` r
u = "https://github.com/ropensci/stplanr/releases/download/0.6.0/r_key_roads_test.Rds"
rnet_disconnected = readRDS(url(u))
sf:::plot.sfc_LINESTRING(rnet_disconnected$geometry)
```

![](https://i.imgur.com/BDQMdSQ.png)

``` r
touching_list = sf::st_intersects(rnet_disconnected)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
g = igraph::graph.adjlist(touching_list)
igraph::is.directed(g)
#> [1] TRUE
g = igraph::as.undirected(g)
# g
# wc = igraph::cluster_walktrap(g)
# wc = igraph::cluster_louvain(g)
# wc = igraph::cluster_fast_greedy(g)
wc = igraph::clusters(g)
m = igraph::membership(wc)
length(unique(m))
#> [1] 193
summary(m)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>    1.00   42.00   68.00   68.65   88.00  193.00
nrow(rnet_disconnected)
#> [1] 5759
length(m)
#> [1] 5759
rnet_disconnected$membership = m
plot(rnet_disconnected["membership"])
```

![](https://i.imgur.com/SJ92VU8.png)

``` r
mapview::mapview(rnet_disconnected["maxspeed"]) # works
```

![](https://i.imgur.com/JKUTqBK.png)

``` r
mapview::mapview(rnet_disconnected["membership"]) # fails
#> Error in dispatch(map, "fitBounds", leaflet = {: Invalid map parameter
```

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
FYI @tim-salabim this minor change fixes it:

```
rnet_disconnected$membership = as.character(rnet_disconnected$membership)
mapview::mapview(rnet_disconnected["membership"]) 
```

So should be a quick fix: coerce to character under certain conditions (if it's integer?)

**Comment by tim-salabim** [comment]
@Robinlovelace thanks for this. You've discovered a bit of an edge-case here. `mapview` breaks here because of legend creation (though not obvious from the error message - so there's room for improvement there), where we have a [switch based on `class`](https://github.com/r-spatial/mapview/blob/master/R/legend.R#L236). Given that
```r
class(rnet_disconnected$membership)
[1] "membership"
```
I am a bit unsure of how to handle this one. I am assuming that this class attribute stem from **igraph** and I do not have any experience with network analysis, so don't know what class, in terms of standard R classes, this should be. Numeric? Character? Factor? Coercing via `as.vector` gives
```
str(as.vector(rnet_disconnected$membership))
 num [1:5759] 1 1 1 1 1 1 1 1 1 1 ...
```
`numeric`, so maybe that should be the fix here? 
However, we should probably ask why such a vector does not inherit from standard R base classes in the first place? We could obviously add another switch for class `membership` but then where do we stop? I am sure there's many more classes out there that we don't cover specifically, so falling back to standard base classes seems like a good idea in general. 

Thoughts?

**Comment by Robinlovelace** [comment]
> `numeric`, so maybe that should be the fix here?

Agreed, I didn't realise that `igraph` was giving me such an unusual output. In fact to counteract this I added the following to a new function in `stplanr` that implements the above method: https://github.com/ropensci/stplanr/blob/master/R/rnet_group.R#L39

```
  if(char) m = as.character(m)
```

I think I should coerce to `numeric` by default to avoid other such edge case errors due to unusual classes. Many thanks for doing the digging, I should have checked the class before reporting.

**Comment by Robinlovelace** [comment]
For completeness, here is a reprex that demonstrates the problem and the solution.

``` r
library(stplanr)
rnet <- stplanr::osm_net_example
touching_list = sf::st_intersects(rnet)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
g = igraph::graph.adjlist(touching_list)
g = igraph::as.undirected(g)
cluster_fun = igraph::clusters
wc = cluster_fun(g)
m = igraph::membership(wc)
class(m)
#> [1] "membership"
m = as.numeric(m)
class(m)
#> [1] "numeric"
rnet$m = m
mapview::mapview(rnet["m"])
```

![](https://i.imgur.com/qyh4hNv.png)

<sup>Created on 2020-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tim-salabim** [comment]
Thanks Robin, I've added a line in the code to coerce via `as.vector`. This should take care of most unusual classes.
