### ISSUE TITLE
Inverse legend labels for dichotomous zcol

### ISSUE THREAD

**Issue by ofr1tz** [r-spatial/mapview#362]
Hi, it seems legend labels are inverted when using a dichotomous factor variable for zcol. Here's an example:

```
require(mapview)
require(tidyverse)

franconia %>% 
	mutate(oberfranken = factor(
		district == "Oberfranken", 
		levels = c(TRUE, FALSE), 
		labels = c("oberfranken", "not oberfranken"))
	) %>% 
	mapview(zcol = "oberfranken")
```

Result:

![oberfranken](https://user-images.githubusercontent.com/11835629/106921017-dfaead00-670b-11eb-9b3a-19fef4ef030b.png)

**Comment by stibu81** [comment]
The same problem also occurs if there are more than two factor levels as the following example shows:

```
library(mapview)
library(dplyr)
library(sf)

breweries %>%
  st_intersection(franconia) %>%
  mutate(district = factor(district,
                           levels = c("Oberfranken",
                                      "Mittelfranken",
                                      "Unterfranken"))) %>%
  mapview(zcol = "district")
```
![image](https://user-images.githubusercontent.com/7131000/108057231-a7d02f80-7052-11eb-8b75-81b8994e5535.png)

It seems that when assigning colours to the values of `distric`, the order of the factor levels is respected, however the labels in the legend are ordered alphabetically. For example, the first colour (purple) is assigned to the points with the first level of the factor ("Oberfranken"), however, in the legend, the label is used that comes first alphabetically ("Mittelfranken").

**Comment by stibu81** [comment]
There really seems to be something wrong with how the colours in the legend are computed. Here another example, where I leave the levels in alphabetic order, but use the same colour for two of the levels:

```
library(mapview)
library(dplyr)
library(sf)

breweries %>%
  st_intersection(franconia) %>%
  mapview(zcol = "district", col.regions = c("red", "red", "blue"))
```
![image](https://user-images.githubusercontent.com/7131000/108073962-ef61b600-7068-11eb-98c8-8e55401989fb.png)

The colours of the points in the map are correct, but the legend uses wrong colours. Instead of using red twice, a gradient is used.

**Comment by tim-salabim** [comment]
I've said it before, Legends are the hill I'm gonna die on... :-)
I'll look into this soon

**Comment by edalfon** [comment]
First of all, many thanks @tim-salabim for such a great package.

I agree with @stibu81, in that there is an issue whenever `zcol` is a
factor variable regardless of the number of levels it has. I’ve found this
particularly problematic when the `zcol` is a discretized numeric
variable.

Just to complement the examples above, let me use the shape area as the
`zcol` variable.

``` r
library(mapview)
#> Warning: package 'mapview' was built under R version 4.0.3
franconia$area <- franconia$SHAPE_AREA * 1000
mapview(franconia, zcol = "area")
```

![](https://i.imgur.com/Lk69FrO.png)

Now, sometimes you may want to discretize the numeric variable, and as
shown below, the issue with the legend can be really problematic. The
labels do not really correspond to the coloring scheme and the order
of the labels is just wrong (lexicographical order instead of the order
of the levels, which is the numerical order underlying these categories.
I did check that using an ordered factor does not make any difference).

``` r
franconia$area2 <- cut(
  x = franconia$area,
  breaks = c(4, 39, 89, 129, 244), # jenks breaks, rounded
  include.lowest = TRUE
)
mapview(franconia, zcol = "area2")
```

![](https://i.imgur.com/HUBx80X.png)

Admittedly, `mapview` handles this nicely using the argument `at`.
And 99% of the time that would be a good solution.

``` r
mapview(franconia, zcol = "area", at = c(4, 39, 89, 129, 244))
```

![](https://i.imgur.com/5H6sPvi.png)

But I wanted to post this example because I think it shows there seems
to be an easy fix. (apologies if I am oversimplifying this because clearly, I am not
familiar with `mapview`’s codebase)

If you compare the two plots above, you can see that:
- the color assignment on the map is correct
- the order of the colors in the legend is also good.

It is just that the labels do not match the colors on the legend, because they follow a
lexicographical order. So I guess somewhere the `zcol` is being coerced to
character, or somehow the levels are being sorted as a character vector.

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tim-salabim** [comment]
Thanks for the very comprehensive example. I will see if I can identify the culprit and hopefully you're right that it is an easy fix... Probably won't happen before the weekend though.

**Comment by tim-salabim** [comment]
Sorry for the long silence! This should now all work as expected (& let's hope I didn't break anything else :-) ):

``` r
require(mapview)
#> Loading required package: mapview
require(poorman) # instead of tidyverse!
#> Loading required package: poorman
#> 
#>   I'd seen my father. He was a poor man, and I watched him do astonishing things.
#>     - Sidney Poitier
#> 
#> Attaching package: 'poorman'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.1.0, PROJ 7.0.0
#> 
#> Attaching package: 'sf'
#> The following object is masked from 'package:poorman':
#> 
#>     %>%

breweries %>%
  st_intersection(franconia) %>%
  mutate(district = factor(district,
                           levels = c("Oberfranken",
                                      "Mittelfranken",
                                      "Unterfranken"))) %>%
  mapview(zcol = "district")
#> although coordinates are longitude/latitude, st_intersection assumes that they are planar
#> Warning: attribute variables are assumed to be spatially constant throughout all
#> geometries
```

![](https://i.imgur.com/gNabTjj.png)

``` r
breweries %>%
  st_intersection(franconia) %>%
  mapview(zcol = "district", col.regions = c("red", "red", "blue"))
#> although coordinates are longitude/latitude, st_intersection assumes that they are planar
#> Warning: attribute variables are assumed to be spatially constant throughout all
#> geometries
```

![](https://i.imgur.com/Rl2ELfa.png)

``` r
franconia$area <- franconia$SHAPE_AREA * 1000
franconia$area2 <- cut(
  x = franconia$area,
  breaks = c(4, 39, 89, 129, 244), # jenks breaks, rounded
  include.lowest = TRUE
)
mapview(franconia, zcol = "area2")
```

![](https://i.imgur.com/9YDpxDC.png)

``` r
mapview(franconia, zcol = "area", at = c(4, 39, 89, 129, 244))
```

![](https://i.imgur.com/mU0tCiM.png)

``` r
franconia %>% 
  mutate(oberfranken = factor(
    district == "Oberfranken", 
    levels = c(TRUE, FALSE), 
    labels = c("oberfranken", "not oberfranken"))
  ) %>% 
  mapview(zcol = "oberfranken", col.regions = c("red", "blue"))
```

![](https://i.imgur.com/Pd18Q2a.png)

<sup>Created on 2021-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ofr1tz** [comment]
Awesome, thanks a lot for the fix!

**Comment by edalfon** [comment]
this is great!!! thanks for the fix @tim-salabim.  I got caught up testing the fix and in the process, I remember another issue I have encountered before, related to the hill I am sure you are NOT gonna die on. https://github.com/r-spatial/mapview/issues/383 Thanks again for a great package!

**Comment by stibu81** [comment]
Thanks also from my side! I've finally managed to check this again with the code where I originally stumbled over this issue. The legends work now flawlessly for my application.
